name: Add Plugins to Cordova Project

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  add-plugins:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout repo
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install Cordova
        run: npm install -g cordova

      - name: ➕ Add Plugins
        run: |
          cordova plugin add cordova-plugin-statusbar

      - name: 💾 Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Added plugins: cordova-plugin-statusbar"
          git push

